url: https://clwdev.github.io
# baseurl: /

# Site settings
title: Clearwater Development
email: support@tuidev.com
description: "Drupal Development for the Travel Industry."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 28A9E0
  secondary: 47C8FF
  secondary-dark: 0D6B93

# Team names, titles and social links
people:
- name: Jeff Hartman
  gravatar: http://www.gravatar.com/avatar/8f2c1dac2cb0cf90cf5f08a1810073ca.png
  position: Senior Developer
  location: Chicago
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/jeffhartman
    - title: drupal
      url: https://www.drupal.org/u/jeff.hartman
    - title: github
      url: https://github.com/jeffhartman
- name: Heath Dutton
  gravatar: http://www.gravatar.com/avatar/150a567c1af6bcdecc0773dc04ae098c.png
  position: Senior Developer / CSM
  location: Tampa
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/heathdutton
    - title: drupal
      url: https://www.drupal.org/u/heathdutton
    - title: github
      url: https://github.com/heathdutton
- name: Jeff George
  gravatar: http://www.gravatar.com/avatar/f3b7a506207021e3d78e3a41f6c3ff20.png
  position: Senior Developer / CSM
  location: Tampa
  social:
    - title: drupal
      url: https://www.drupal.org/u/jeff.george
    - title: github	
      url: https://github.com/jeffgeorge
- name: Scott Shipman
  gravatar: http://www.gravatar.com/avatar/ac6c5ddb4dbfa966a6a7dd63c14d5f81.png
  position: Senior Developer / CSM
  location: Dunedin
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/kscottshipman
    - title: drupal
      url: https://www.drupal.org/u/scott-shipman
    - title: anchor	
      url: http://ibuilddrupalsites.com/
- name: Jordan Schinella
  gravatar: http://www.gravatar.com/avatar/87680c18bc023fcb6bf254daa68abb6d.png
  position: Security Specialist / Developer
  location: Tampa
  social:
   - title: linkedin
     url: http://www.linkedin.com/in/jordanschinella
   - title: github
     url: https://github.com/jordanvector
   - title: anchor
     url: http://vector.solutions
- name: John Jennings
  gravatar: http://www.gravatar.com/avatar/5c0061a50202fe333a839e230bec9bc6.png
  position: Front-End Specialist / Developer
  location: Tampa
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/jcjconnect
    - title: github	
      url: https://github.com/thatracerguy

#
#- name: Diana Petersen
#  gravatar: 3
#  position: Lead Developer
#  location: Tampa
#  social:
#    - title: linkedin
#      url: #
#    - title: drupal
#      url: #
#    - title: github
#      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#social:
#  - title: twitter
#    url: http://twitter.com/jekyllrb
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
#address:
#  - line: 3481 Melrose Place
#  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
